"""Claude AI analyst layer for trade signal validation."""

import asyncio
import json
import logging
from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, Optional

import anthropic

if TYPE_CHECKING:
    from bot.context_builder import MarketContext
    from bot.strategy import TradeSignal

logger = logging.getLogger(__name__)


class AIDecision(Enum):
    """AI analyst decision on a candidate trade signal."""

    EXECUTE = "execute"  # Claude agrees, proceed with trade
    SKIP = "skip"  # Claude disagrees, cancel this signal
    WAIT = "wait"  # Insufficient data, wait for next candle


@dataclass
class CandidateSignal:
    """A candidate trade signal prepared for AI analysis."""

    side: str  # "long" or "short"
    entry_price: float
    stop_loss: float
    take_profit: float
    sl_pct: float  # SL distance as percentage
    tp_pct: float  # TP distance as percentage
    rr_ratio: float


@dataclass
class AnalystResult:
    """Result of AI analyst evaluation."""

    decision: AIDecision
    confidence: float  # 0.0 – 1.0
    reasoning: str  # Short explanation
    risk_flags: list[str]  # e.g., ["high_funding_rate", "bearish_news"]
    override: bool  # True if Claude overrides the original signal


SYSTEM_PROMPT = """
You are a professional crypto futures trading analyst specializing in BTC/USDT perpetual contracts on Bybit.
Your role is to validate a candidate trade signal generated by a rule-based strategy.
You are NOT generating the signal yourself — you are providing a second opinion.

## Your Job
Analyze the provided market context and decide whether to:
- EXECUTE: The signal is supported by context, proceed with the trade
- SKIP: The signal looks unreliable given current conditions, cancel it
- WAIT: Insufficient clarity, hold for next candle

## What You Analyze
1. Technical confluence — do indicators align consistently across timeframes?
2. Market microstructure — funding rate extreme? OI diverging from price?
3. News sentiment — any recent headline that contradicts the signal direction?
4. Risk context — bot already in drawdown today? Consecutive losses?
5. Orderbook pressure — does bid/ask imbalance support the signal direction?

## Decision Criteria
EXECUTE when:
- 15m and 1h trend agree with signal direction
- RSI not at extreme (not >75 for long, not <25 for short)
- Funding rate not strongly opposing (e.g. very positive rate for a long = longs paying heavily)
- No major negative news for a long (no major positive news for a short)
- Orderbook imbalance >= 0.55 for long, <= 0.45 for short
- Bot not already at >1.5% daily loss

SKIP when any of these apply:
- Price action contradicts 1h trend
- Funding rate extreme (>0.1% for long entry, <-0.1% for short entry)
- Breaking negative news for long direction (or positive news for short)
- 3+ consecutive losses already today
- OI dropping while price rising (divergence warning for longs)

WAIT when:
- Mixed signals — some factors support, some oppose, but no strong conviction either way
- News just broke and market hasn't reacted yet

## Output Format (STRICT JSON — no markdown, no explanation outside JSON)
{
  "decision": "execute" | "skip" | "wait",
  "confidence": 0.0–1.0,
  "reasoning": "1–2 sentences max",
  "risk_flags": ["flag1", "flag2"],
  "override": true | false
}

## Constraints
- Response must be valid JSON only
- reasoning must be under 100 words
- Never recommend changing leverage or position size
- Never suggest entry price adjustments — that's the strategy's job
- If you are uncertain, default to SKIP (conservative bias)
"""


def build_user_prompt(signal: CandidateSignal, ctx: "MarketContext") -> str:
    """Build the user prompt for Claude from signal and market context.

    Args:
        signal: The candidate trade signal.
        ctx: Current market context.

    Returns:
        Formatted prompt string.
    """

    def _format_candles(candles: list[dict]) -> str:
        lines = []
        for c in candles:
            lines.append(
                f"  O:{c.get('open', 0):.2f} H:{c.get('high', 0):.2f} "
                f"L:{c.get('low', 0):.2f} C:{c.get('close', 0):.2f} "
                f"V:{c.get('volume', 0):.0f}"
            )
        return "\n".join(lines)

    candles_summary = _format_candles(ctx.candles_15m[-5:]) if ctx.candles_15m else "No data"
    news_block = "\n".join(f"- {h}" for h in ctx.news_headlines[:3]) if ctx.news_headlines else "No significant news"

    ema_direction = "EMA bullish cross" if ctx.ema_9 > ctx.ema_21 else "EMA bearish cross"
    trend_position = "ABOVE" if signal.entry_price > ctx.ema_50_1h else "BELOW"

    return f"""
## Candidate Signal
Direction : {signal.side.upper()}
Entry price: {signal.entry_price:,.2f}
Stop loss  : {signal.stop_loss:,.2f}  ({signal.sl_pct:.2f}% from entry)
Take profit: {signal.take_profit:,.2f}  ({signal.tp_pct:.2f}% from entry)
R:R ratio  : 1:{signal.rr_ratio:.1f}

## Recent 15m Candles
{candles_summary}

## Technical Indicators (15m)
EMA(9/21)  : {ctx.ema_9:.2f} / {ctx.ema_21:.2f}  → {ema_direction}
RSI(14)    : {ctx.rsi_14:.1f}
ATR(14)    : {ctx.atr_14:.2f}
Volume ratio: {ctx.volume_ratio:.2f}x MA20

## 1h Trend
EMA(50) 1h : {ctx.ema_50_1h:.2f}  → Price is {trend_position} 1h trend

## Market Microstructure
Funding rate     : {ctx.funding_rate:.4f}%  (8h rate)
OI change (1h)   : {ctx.open_interest_change:+.2f}%
Orderbook imbal. : {ctx.orderbook_imbalance:.3f}  (>0.5 = bid heavy)

## Recent News (last 2h)
{news_block}

## Bot State Today
Daily PnL      : {ctx.daily_pnl_pct:+.2f}%
Consec. losses : {ctx.consecutive_losses}
Last trade     : {ctx.hours_since_last_trade:.1f}h ago

Analyze and respond with JSON only.
""".strip()


def _parse_response(text: str) -> AnalystResult:
    """Parse Claude's JSON response into an AnalystResult.

    Args:
        text: Raw response text from Claude.

    Returns:
        Parsed AnalystResult.

    Raises:
        ValueError: If response cannot be parsed.
    """
    # Strip any markdown code fences
    cleaned = text.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        cleaned = "\n".join(lines[1:-1]) if len(lines) > 2 else cleaned

    data = json.loads(cleaned)

    decision_str = data.get("decision", "skip").lower()
    try:
        decision = AIDecision(decision_str)
    except ValueError:
        decision = AIDecision.SKIP

    confidence = float(data.get("confidence", 0.0))
    confidence = max(0.0, min(1.0, confidence))

    return AnalystResult(
        decision=decision,
        confidence=confidence,
        reasoning=str(data.get("reasoning", "")),
        risk_flags=list(data.get("risk_flags", [])),
        override=bool(data.get("override", False)),
    )


class AIAnalyst:
    """Claude AI analyst for validating trade signals.

    Calls Claude API to get a second opinion on rule-based signals.
    Falls back to SKIP on any error to maintain conservative bias.
    """

    def __init__(
        self,
        api_key: str,
        confidence_threshold: float = 0.65,
        model: str = "claude-sonnet-4-6",
        max_tokens: int = 256,
        timeout_seconds: float = 8.0,
        fallback_on_timeout: str = "skip",
        enabled: bool = True,
    ) -> None:
        """Initialize the AI analyst.

        Args:
            api_key: Anthropic API key.
            confidence_threshold: Minimum confidence to execute.
            model: Claude model to use.
            max_tokens: Maximum response tokens.
            timeout_seconds: API call timeout.
            fallback_on_timeout: Default decision on timeout ("skip" or "execute").
            enabled: Whether AI layer is active.
        """
        self.confidence_threshold = confidence_threshold
        self.model = model
        self.max_tokens = max_tokens
        self.timeout_seconds = timeout_seconds
        self.fallback_on_timeout = fallback_on_timeout
        self.enabled = enabled

        if enabled:
            self.client = anthropic.AsyncAnthropic(api_key=api_key)
        else:
            self.client = None

    async def analyze(
        self,
        signal: CandidateSignal,
        context: "MarketContext",
    ) -> AnalystResult:
        """Analyze a candidate signal with Claude.

        Args:
            signal: The candidate trade signal.
            context: Current market context.

        Returns:
            AnalystResult with decision, confidence, reasoning.
        """
        # Pass-through mode when disabled
        if not self.enabled:
            logger.info("ai_layer_disabled", extra={"action": "pass_through"})
            return AnalystResult(
                decision=AIDecision.EXECUTE,
                confidence=1.0,
                reasoning="AI layer disabled, passing through all signals",
                risk_flags=[],
                override=False,
            )

        user_prompt = build_user_prompt(signal, context)

        try:
            response = await asyncio.wait_for(
                self._call_api(user_prompt),
                timeout=self.timeout_seconds,
            )
            result = _parse_response(response)

            logger.info(
                "ai_decision",
                extra={
                    "decision": result.decision.value,
                    "confidence": result.confidence,
                    "reasoning": result.reasoning,
                    "risk_flags": result.risk_flags,
                    "override": result.override,
                },
            )
            return result

        except asyncio.TimeoutError:
            logger.warning(
                "ai_timeout",
                extra={
                    "timeout_seconds": self.timeout_seconds,
                    "fallback": self.fallback_on_timeout,
                },
            )
            return self._fallback_result("API timeout")

        except json.JSONDecodeError as e:
            logger.error("ai_parse_error", extra={"error": str(e)})
            return self._fallback_result(f"JSON parse error: {e}")

        except anthropic.APIError as e:
            logger.error("ai_api_error", extra={"error": str(e)})
            return self._fallback_result(f"API error: {e}")

        except Exception as e:
            logger.error("ai_unexpected_error", extra={"error": str(e)})
            return self._fallback_result(f"Unexpected error: {e}")

    async def _call_api(self, user_prompt: str) -> str:
        """Make the actual API call to Claude.

        Args:
            user_prompt: Formatted user prompt.

        Returns:
            Raw response text.
        """
        message = await self.client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        return message.content[0].text

    def _fallback_result(self, reason: str) -> AnalystResult:
        """Create a fallback result when the API call fails.

        Args:
            reason: Reason for fallback.

        Returns:
            Conservative AnalystResult (defaults to SKIP).
        """
        fallback_decision = AIDecision.SKIP
        if self.fallback_on_timeout == "execute":
            fallback_decision = AIDecision.EXECUTE

        return AnalystResult(
            decision=fallback_decision,
            confidence=0.0,
            reasoning=f"Fallback: {reason}",
            risk_flags=["api_fallback"],
            override=False,
        )
