/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/portfolio/summary": {
    /**
     * Portfolio Summary
     * @description Aggregated portfolio-level stats.
     */
    get: operations["portfolio_summary_api_portfolio_summary_get"];
  };
  "/api/bots": {
    /**
     * List Bots
     * @description List all bots with per-symbol summary stats.
     */
    get: operations["list_bots_api_bots_get"];
  };
  "/api/bots/{symbol}": {
    /**
     * Bot Detail
     * @description Detail for a single bot — stats + recent trades.
     */
    get: operations["bot_detail_api_bots__symbol__get"];
  };
  "/api/trades": {
    /**
     * List Trades
     * @description List closed trades, optionally filtered by symbol.
     */
    get: operations["list_trades_api_trades_get"];
  };
  "/api/equity": {
    /**
     * Equity Curve
     * @description Equity curve data points.
     */
    get: operations["equity_curve_api_equity_get"];
  };
  "/api/daily-pnl": {
    /**
     * Daily Pnl
     * @description Daily PnL aggregated by UTC date.
     */
    get: operations["daily_pnl_api_daily_pnl_get"];
  };
  "/api/ai/calibration": {
    /**
     * Ai Calibration
     * @description AI advisor calibration stats per symbol + portfolio-level aggregate.
     *
     * Uses get_calibration_stats() for the influence ladder to avoid re-deriving
     * the same logic in the router.
     */
    get: operations["ai_calibration_api_ai_calibration_get"];
  };
  "/api/logs": {
    /**
     * Get Logs
     * @description Recent log lines, optionally filtered by level/search.
     */
    get: operations["get_logs_api_logs_get"];
  };
  "/api/close-reasons": {
    /**
     * Close Reasons
     * @description Close-reason breakdown with total PnL and sign colouring.
     */
    get: operations["close_reasons_api_close_reasons_get"];
  };
  "/api/trade-gate": {
    /**
     * Trade Gate
     * @description Per-symbol attribution gate (FREE / MIXED) with sample-size guard.
     */
    get: operations["trade_gate_api_trade_gate_get"];
  };
  "/api/risk": {
    /**
     * Open Risk
     * @description Open position risk (SL distance, unprotected flag, aggregate notional/max_sl_loss).
     */
    get: operations["open_risk_api_risk_get"];
  };
  "/api/calendar": {
    /**
     * Calendar Pnl
     * @description Daily PnL calendar heatmap for a given month.
     */
    get: operations["calendar_pnl_api_calendar_get"];
  };
  "/api/heatmap": {
    /**
     * Heatmap
     * @description Hour-of-day x day-of-week PnL heatmap (UTC bucketing).
     */
    get: operations["heatmap_api_heatmap_get"];
  };
  "/api/bots/{symbol}/mode": {
    /**
     * Set Bot Mode
     * @description Set mode for a single bot (NORMAL | GRACEFUL_STOP | TP_ONLY | PANIC).
     *
     * Args:
     *     symbol: sym_clean'd symbol in the URL path (e.g. BTCUSDT).
     *     body: ModeRequest with ``mode`` field and optional ``confirm_panic``.
     *
     * Returns:
     *     ModeResponse indicating acceptance and the resulting mode.
     *
     * Raises:
     *     HTTPException 400: Symbol not in roster or invalid format.
     *     HTTPException 422: Unknown mode string.
     *     HTTPException 401: Missing or wrong X-Dash-Token.
     */
    post: operations["set_bot_mode_api_bots__symbol__mode_post"];
  };
  "/api/bots/mode/bulk": {
    /**
     * Set Bulk Mode
     * @description Set mode for multiple (or all) roster bots in one request.
     *
     * If ``symbols`` is empty, the mode is applied to every bot in the roster.
     *
     * PANIC debounce: a 2nd bulk PANIC within ``CCBT_PANIC_DEBOUNCE_S`` seconds
     * returns 429 to prevent accidental double-clicks from closing everything twice.
     *
     * Args:
     *     body: BulkModeRequest with ``symbols`` list (empty = all) and ``mode``.
     *
     * Returns:
     *     BulkModeResponse with per-symbol ModeResponse entries.
     *
     * Raises:
     *     HTTPException 422: Unknown mode string.
     *     HTTPException 429: Rapid duplicate bulk PANIC.
     *     HTTPException 401: Missing or wrong X-Dash-Token.
     */
    post: operations["set_bulk_mode_api_bots_mode_bulk_post"];
  };
  "/api/candles": {
    /**
     * Get Candles
     * @description Persisted OHLCV candles + indicators for a symbol.
     *
     * Returns {available: false} when no candles are persisted.
     * The bot writes to bot_ohlcv whenever it fetches OHLCV from the exchange.
     * The dashboard NEVER calls the exchange directly.
     */
    get: operations["get_candles_api_candles_get"];
  };
  "/api/health": {
    /**
     * Health
     * @description Liveness probe — confirms the API process is up.
     */
    get: operations["health_api_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AICalibrationAggregate
     * @description Portfolio-level AI calibration aggregate (weighted across all symbols).
     */
    AICalibrationAggregate: {
      /**
       * Total Decisions
       * @default 0
       */
      total_decisions?: number;
      /**
       * Decided Trades
       * @default 0
       */
      decided_trades?: number;
      /**
       * Weighted Accuracy Pct
       * @default 0
       */
      weighted_accuracy_pct?: number;
      /**
       * Avg Influence Factor
       * @default 1
       */
      avg_influence_factor?: number;
    };
    /**
     * AICalibrationResponse
     * @description GET /api/ai/calibration
     */
    AICalibrationResponse: {
      /** Rows */
      rows: components["schemas"]["AICalibrationRow"][];
      aggregate?: components["schemas"]["AICalibrationAggregate"] | null;
    };
    /** AICalibrationRow */
    AICalibrationRow: {
      /** Symbol */
      symbol: string;
      /** Total Decisions */
      total_decisions: number;
      /** Correct */
      correct: number;
      /** Accuracy Pct */
      accuracy_pct: number;
      /** Influence Factor */
      influence_factor: number;
    };
    /**
     * BotDetailResponse
     * @description GET /api/bots/{symbol}
     */
    BotDetailResponse: {
      /** Symbol */
      symbol: string;
      summary: components["schemas"]["BotRow"];
      /** Recent Trades */
      recent_trades: components["schemas"]["TradeRow"][];
    };
    /**
     * BotListResponse
     * @description GET /api/bots
     */
    BotListResponse: {
      /** Bots */
      bots: components["schemas"]["BotRow"][];
    };
    /**
     * BotRow
     * @description One row in GET /api/bots.
     */
    BotRow: {
      /** Symbol */
      symbol: string;
      /** Strategy */
      strategy: string | null;
      /** Timeframe */
      timeframe: string | null;
      /** Status */
      status: string | null;
      /** Position Side */
      position_side: string | null;
      /** Position Size */
      position_size: number | null;
      /** Unrealized Pnl */
      unrealized_pnl: number | null;
      /** Total Pnl */
      total_pnl: number;
      /** Win Rate Pct */
      win_rate_pct: number;
      /** Profit Factor */
      profit_factor: number;
      /** Trade Count */
      trade_count: number;
      /** Last Updated */
      last_updated: string | null;
      /** Mode */
      mode: string | null;
      /**
       * Error Count
       * @description Consecutive error count from bot_health. 0 when healthy.
       * @default 0
       */
      error_count?: number;
    };
    /**
     * BulkModeRequest
     * @description POST /api/bots/mode/bulk
     */
    BulkModeRequest: {
      /** Symbols */
      symbols: string[];
      /** Mode */
      mode: string;
      /** Confirm Panic */
      confirm_panic?: boolean | null;
    };
    /** BulkModeResponse */
    BulkModeResponse: {
      /** Results */
      results: components["schemas"]["ModeResponse"][];
    };
    /** CalendarCell */
    CalendarCell: {
      /** Date */
      date: string;
      /** Pnl */
      pnl: number;
      /** Trade Count */
      trade_count: number;
      /**
       * Win Rate Pct
       * @default 0
       */
      win_rate_pct?: number;
    };
    /**
     * CalendarResponse
     * @description GET /api/calendar?symbol=&year=&month=
     */
    CalendarResponse: {
      /** Symbol */
      symbol: string | null;
      /** Year */
      year: number;
      /** Month */
      month: number;
      /** Cells */
      cells: components["schemas"]["CalendarCell"][];
    };
    /**
     * CandleBar
     * @description One OHLCV candle with indicator snapshots.
     */
    CandleBar: {
      /** Ts */
      ts: number;
      /** Open */
      open: number;
      /** High */
      high: number;
      /** Low */
      low: number;
      /** Close */
      close: number;
      /** Volume */
      volume: number;
      /** Ema9 */
      ema9: number | null;
      /** Ema21 */
      ema21: number | null;
      /** Rsi14 */
      rsi14: number | null;
    };
    /**
     * CandlesResponse
     * @description GET /api/candles?symbol=&timeframe=&limit=
     *
     * When available=False the candles list is empty and the UI shows a fallback.
     */
    CandlesResponse: {
      /** Available */
      available: boolean;
      /** Symbol */
      symbol: string | null;
      /** Timeframe */
      timeframe: string | null;
      /**
       * Candles
       * @default []
       */
      candles?: components["schemas"]["CandleBar"][];
    };
    /** CloseReasonItem */
    CloseReasonItem: {
      /** Reason */
      reason: string;
      /** Count */
      count: number;
      /** Total Pnl */
      total_pnl: number;
      /** Pnl Positive */
      pnl_positive: boolean;
    };
    /**
     * CloseReasonResponse
     * @description GET /api/close-reasons?symbol=
     */
    CloseReasonResponse: {
      /** Symbol */
      symbol: string | null;
      /** Breakdown */
      breakdown: components["schemas"]["CloseReasonItem"][];
    };
    /** DailyPnlPoint */
    DailyPnlPoint: {
      /** Date */
      date: string;
      /** Pnl */
      pnl: number;
      /** Trade Count */
      trade_count: number;
    };
    /**
     * DailyPnlResponse
     * @description GET /api/daily-pnl?symbol=
     */
    DailyPnlResponse: {
      /** Symbol */
      symbol: string | null;
      /** Days */
      days: components["schemas"]["DailyPnlPoint"][];
    };
    /** EquityPoint */
    EquityPoint: {
      /** Timestamp */
      timestamp: string;
      /** Equity */
      equity: number;
      /** Cumulative Pnl */
      cumulative_pnl: number;
    };
    /**
     * EquityResponse
     * @description GET /api/equity?symbol=
     */
    EquityResponse: {
      /** Symbol */
      symbol: string | null;
      /** Points */
      points: components["schemas"]["EquityPoint"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description GET /api/health
     */
    HealthResponse: {
      /**
       * Status
       * @default ok
       */
      status?: string;
      /**
       * Db Exists
       * @default false
       */
      db_exists?: boolean;
      /**
       * Version
       * @default 2
       */
      version?: string;
    };
    /** HeatmapCell */
    HeatmapCell: {
      /** Hour */
      hour: number;
      /** Dow */
      dow: number;
      /** Pnl - total_pnl for the cell (kept for backward compat) */
      pnl: number;
      /** Avg Pnl - average pnl per trade (true expectancy; use for colouring/display) */
      avg_pnl: number;
      /** Trade Count */
      trade_count: number;
      /** Win Rate Pct */
      win_rate_pct: number;
    };
    /**
     * HeatmapResponse
     * @description GET /api/heatmap?symbol=&bucket_hours=
     */
    HeatmapResponse: {
      /** Symbol */
      symbol: string | null;
      /** Bucket Hours */
      bucket_hours: number;
      /** Cells */
      cells: components["schemas"]["HeatmapCell"][];
    };
    /** LogLine */
    LogLine: {
      /** Timestamp */
      timestamp: string | null;
      /** Level */
      level: string | null;
      /** Message */
      message: string;
      /** Raw */
      raw: string;
    };
    /**
     * LogsResponse
     * @description GET /api/logs?level=&search=&limit=
     */
    LogsResponse: {
      /** Lines */
      lines: components["schemas"]["LogLine"][];
      /** Total Returned */
      total_returned: number;
    };
    /**
     * ModeRequest
     * @description POST /api/bots/{symbol}/mode
     */
    ModeRequest: {
      /** Mode */
      mode: string;
      /** Confirm Panic */
      confirm_panic?: boolean | null;
    };
    /** ModeResponse */
    ModeResponse: {
      /** Symbol */
      symbol: string;
      /** Mode */
      mode: string;
      /** Accepted */
      accepted: boolean;
      /** Message */
      message: string | null;
    };
    /**
     * OpenRiskResponse
     * @description GET /api/risk?symbol=
     */
    OpenRiskResponse: {
      /** Symbol */
      symbol: string | null;
      /** Rows */
      rows: components["schemas"]["OpenRiskRow"][];
      /** Unprotected Count */
      unprotected_count: number;
      /**
       * Notional
       * @default 0
       */
      notional?: number;
      /**
       * Max Sl Loss
       * @default 0
       */
      max_sl_loss?: number;
    };
    /** OpenRiskRow */
    OpenRiskRow: {
      /** Symbol */
      symbol: string;
      /** Side */
      side: string | null;
      /** Entry Price */
      entry_price: number | null;
      /** Stop Loss */
      stop_loss: number | null;
      /** Position Size */
      position_size: number | null;
      /** Stop Distance Pct */
      stop_distance_pct: number | null;
      /** Unprotected */
      unprotected: boolean;
    };
    /**
     * PortfolioSummaryResponse
     * @description GET /api/portfolio/summary — top-level portfolio stats.
     */
    PortfolioSummaryResponse: {
      /** Total Trades */
      total_trades: number;
      /** Closed Trades */
      closed_trades: number;
      /** Win Rate Pct */
      win_rate_pct: number;
      /** Profit Factor */
      profit_factor: number;
      /** Total Pnl */
      total_pnl: number;
      /** Best Bot */
      best_bot: string | null;
      /** Worst Bot */
      worst_bot: string | null;
      /** Active Bots */
      active_bots: number;
    };
    /**
     * TradeGateResponse
     * @description GET /api/trade-gate
     */
    TradeGateResponse: {
      summary: components["schemas"]["TradeGateSummary"];
      /** Rows */
      rows: components["schemas"]["TradeGateRow"][];
    };
    /** TradeGateRow */
    TradeGateRow: {
      /** Symbol */
      symbol: string;
      /** Config Count */
      config_count: number;
      /** Trade Count */
      trade_count: number;
      /** Profit Factor */
      profit_factor: number;
      /** Win Rate Pct */
      win_rate_pct: number;
      /** Reward To Avgloss */
      reward_to_avgloss: number | null;
      /** Real R */
      real_r: number | null;
      /** Verdict */
      verdict: string;
      /** Meets Min Trades */
      meets_min_trades: boolean;
    };
    /** TradeGateSummary */
    TradeGateSummary: {
      /** N Meeting Min */
      n_meeting_min: number;
      /** N Total */
      n_total: number;
      /** Min Trades Threshold */
      min_trades_threshold: number;
    };
    /**
     * TradeListResponse
     * @description GET /api/trades?symbol=&limit=
     */
    TradeListResponse: {
      /** Trades */
      trades: components["schemas"]["TradeRow"][];
      /** Total */
      total: number;
    };
    /**
     * TradeRow
     * @description One closed trade row.
     */
    TradeRow: {
      /** Id */
      id: number | null;
      /** Symbol */
      symbol: string;
      /** Side */
      side: string | null;
      /** Entry Price */
      entry_price: number | null;
      /** Exit Price */
      exit_price: number | null;
      /** Pnl */
      pnl: number | null;
      /** Pnl Pct */
      pnl_pct: number | null;
      /** Close Reason */
      close_reason: string | null;
      /** Timestamp */
      timestamp: string | null;
      /** Duration Seconds */
      duration_seconds: number | null;
      /** Strategy */
      strategy: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Portfolio Summary
   * @description Aggregated portfolio-level stats.
   */
  portfolio_summary_api_portfolio_summary_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioSummaryResponse"];
        };
      };
    };
  };
  /**
   * List Bots
   * @description List all bots with per-symbol summary stats.
   */
  list_bots_api_bots_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BotListResponse"];
        };
      };
    };
  };
  /**
   * Bot Detail
   * @description Detail for a single bot — stats + recent trades.
   */
  bot_detail_api_bots__symbol__get: {
    parameters: {
      path: {
        symbol: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BotDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Trades
   * @description List closed trades, optionally filtered by symbol.
   */
  list_trades_api_trades_get: {
    parameters: {
      query?: {
        symbol?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TradeListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Equity Curve
   * @description Equity curve data points.
   */
  equity_curve_api_equity_get: {
    parameters: {
      query?: {
        symbol?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EquityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Daily Pnl
   * @description Daily PnL aggregated by UTC date.
   */
  daily_pnl_api_daily_pnl_get: {
    parameters: {
      query?: {
        symbol?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DailyPnlResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Ai Calibration
   * @description AI advisor calibration stats per symbol + portfolio-level aggregate.
   *
   * Uses get_calibration_stats() for the influence ladder to avoid re-deriving
   * the same logic in the router.
   */
  ai_calibration_api_ai_calibration_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AICalibrationResponse"];
        };
      };
    };
  };
  /**
   * Get Logs
   * @description Recent log lines, optionally filtered by level/search.
   */
  get_logs_api_logs_get: {
    parameters: {
      query?: {
        level?: string | null;
        search?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LogsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Close Reasons
   * @description Close-reason breakdown with total PnL and sign colouring.
   */
  close_reasons_api_close_reasons_get: {
    parameters: {
      query?: {
        symbol?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CloseReasonResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Trade Gate
   * @description Per-symbol attribution gate (FREE / MIXED) with sample-size guard.
   */
  trade_gate_api_trade_gate_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TradeGateResponse"];
        };
      };
    };
  };
  /**
   * Open Risk
   * @description Open position risk (SL distance, unprotected flag, aggregate notional/max_sl_loss).
   */
  open_risk_api_risk_get: {
    parameters: {
      query?: {
        symbol?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OpenRiskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Calendar Pnl
   * @description Daily PnL calendar heatmap for a given month.
   */
  calendar_pnl_api_calendar_get: {
    parameters: {
      query?: {
        symbol?: string | null;
        year?: number | null;
        month?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CalendarResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Heatmap
   * @description Hour-of-day x day-of-week PnL heatmap (UTC bucketing).
   */
  heatmap_api_heatmap_get: {
    parameters: {
      query?: {
        symbol?: string | null;
        bucket_hours?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HeatmapResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Set Bot Mode
   * @description Set mode for a single bot (NORMAL | GRACEFUL_STOP | TP_ONLY | PANIC).
   *
   * Args:
   *     symbol: sym_clean'd symbol in the URL path (e.g. BTCUSDT).
   *     body: ModeRequest with ``mode`` field and optional ``confirm_panic``.
   *
   * Returns:
   *     ModeResponse indicating acceptance and the resulting mode.
   *
   * Raises:
   *     HTTPException 400: Symbol not in roster or invalid format.
   *     HTTPException 422: Unknown mode string.
   *     HTTPException 401: Missing or wrong X-Dash-Token.
   */
  set_bot_mode_api_bots__symbol__mode_post: {
    parameters: {
      header?: {
        "X-Dash-Token"?: string | null;
      };
      path: {
        symbol: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ModeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Set Bulk Mode
   * @description Set mode for multiple (or all) roster bots in one request.
   *
   * If ``symbols`` is empty, the mode is applied to every bot in the roster.
   *
   * PANIC debounce: a 2nd bulk PANIC within ``CCBT_PANIC_DEBOUNCE_S`` seconds
   * returns 429 to prevent accidental double-clicks from closing everything twice.
   *
   * Args:
   *     body: BulkModeRequest with ``symbols`` list (empty = all) and ``mode``.
   *
   * Returns:
   *     BulkModeResponse with per-symbol ModeResponse entries.
   *
   * Raises:
   *     HTTPException 422: Unknown mode string.
   *     HTTPException 429: Rapid duplicate bulk PANIC.
   *     HTTPException 401: Missing or wrong X-Dash-Token.
   */
  set_bulk_mode_api_bots_mode_bulk_post: {
    parameters: {
      header?: {
        "X-Dash-Token"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkModeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BulkModeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Candles
   * @description Persisted OHLCV candles + indicators for a symbol.
   *
   * Returns {available: false} when no candles are persisted.
   * The bot writes to bot_ohlcv whenever it fetches OHLCV from the exchange.
   * The dashboard NEVER calls the exchange directly.
   */
  get_candles_api_candles_get: {
    parameters: {
      query?: {
        symbol?: string | null;
        timeframe?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CandlesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health
   * @description Liveness probe — confirms the API process is up.
   */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
